
name: test

on:
  push:
    branches: [ macostest ]
  pull_request:
    branches: [ macostest ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        python-version: [3.9]
        python-arch: [x64]

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.python-arch }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools
        python -m pip install .[test]
        
        
    steps:
    - uses: actions/checkout@v2
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3

    - name: Test
      run: |
        python -m pytest --cov=pgo --cov-report=xml

    - name: Codecov
      uses: codecov/codecov-action@v1.2.1
