
name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [pypy-3.6, 3.6, pypy-3.7, 3.7, 3.8, 3.9, 3.10-dev]
        python-arch: [x86, x64]
        
        exclude:
          - os: ubuntu-latest
            python-arch: x86
          - os: macos-latest
            python-arch: x86

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python-version }}-${{ matrix.python-arch }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.python-arch }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools
        python -m pip install .[test]

    - name: Test
      run: |
        python3 -m pytest --cov=pgo --cov-report=xml

    - name: Codecov
      uses: codecov/codecov-action@v1.2.1
